[package]
name = 'googletest'
version = '3fbe4db9a39291ae8d7a9c5f1d75896bb4c5a18f'
git = 'https://github.com/google/googletest.git'

[library]
include = [
    'googletest/include',
    'googletest',
    'googlemock/include',
    'googlemock',
]
sources = ['googletest/src/gtest-all.cc', 'googlemock/src/gmock-all.cc']
