[library.argparse]
base_path = 'deps\p-ranav-argparse-v3.2'
cflags = [ '-DDEBUG', '-g', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\p-ranav-argparse-v3.2\include' ]
modules = []
sources = []

[library.cracklib]
base_path = 'deps\evanwporter-cracklib-v0.0.3'
cflags = [ '-DDEBUG', '-g', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\evanwporter-cracklib-v0.0.3\include' ]
modules = []
sources = [ 'deps\evanwporter-cracklib-v0.0.3\src\cracklib.cpp' ]

[library.glob]
base_path = 'deps\p-ranav-glob-v0.3'
cflags = [ '-DDEBUG', '-g', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\p-ranav-glob-v0.3\single_include' ]
modules = []
sources = []

[library.json]
base_path = 'deps\nlohmann-json-v3.11.3'
cflags = [ '-DDEBUG', '-g', '/DDEBUG', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\nlohmann-json-v3.11.3\single_include' ]
modules = []
sources = []

[library.spdlog]
base_path = 'deps\gabime-spdlog-v1.15.1'
cflags = [ '-DDEBUG', '-g', '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\gabime-spdlog-v1.15.1\include' ]
modules = []
sources = [
    'deps\gabime-spdlog-v1.15.1\src\async.cpp',
    'deps\gabime-spdlog-v1.15.1\src\cfg.cpp',
    'deps\gabime-spdlog-v1.15.1\src\spdlog.cpp',
    'deps\gabime-spdlog-v1.15.1\src\color_sinks.cpp',
    'deps\gabime-spdlog-v1.15.1\src\stdout_sinks.cpp',
    'deps\gabime-spdlog-v1.15.1\src\bundled_fmtlib_format.cpp',
    'deps\gabime-spdlog-v1.15.1\src\file_sinks.cpp'
]

[library.zip]
base_path = 'deps\kuba---zip-v0.3.3'
cflags = [ '-DDEBUG', '-g', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'deps\kuba---zip-v0.3.3\src' ]
modules = []
sources = [ 'deps\kuba---zip-v0.3.3\src\zip.c' ]

[library.muuk]
base_path = ''
cflags = [
    '-DDEBUG',
    '-g',
    '/DDEBUG',
    '/DSPDLOG_COMPILED_LIB',
    '/DSPDLOG_USE_STD_FORMAT',
    '/EHsc',
    '/FS',
    '/W4',
    '/std:c++20',
    '/utf-8'
]
include = [
    'deps\evanwporter-cracklib-v0.0.3\include',
    'deps\gabime-spdlog-v1.15.1\include',
    'deps\kuba---zip-v0.3.3\src',
    'deps\nlohmann-json-v3.11.3\single_include',
    'deps\p-ranav-argparse-v3.2\include',
    'deps\p-ranav-glob-v0.3\single_include',
    'include'
]
modules = []
sources = [
    'src\muuk.cpp',
    'src\util.cpp',
    'src\logger.cpp',
    'src\muukfiler.cpp',
    'src\muukbuilder.cpp',
    'src\ninjagen.cpp',
    'src\muuklockgen.cpp'
]

[build.bin]
base_path = ''
cflags = [ '/DDEBUG', '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/FS', '/std:c++20', '/utf-8' ]
include = [
    'deps\evanwporter-cracklib-v0.0.3\include',
    'deps\gabime-spdlog-v1.15.1\include',
    'deps\kuba---zip-v0.3.3\src',
    'deps\nlohmann-json-v3.11.3\single_include',
    'deps\p-ranav-argparse-v3.2\include',
    'deps\p-ranav-glob-v0.3\single_include',
    'include'
]
modules = []
sources = [ 'src\main.cpp' ]

[library.googletest]
base_path = 'deps\google-googletest-v1.15.2'
cflags = [ '-DDEBUG', '-g', '/EHsc', '/FS', '/W4', '/std:c++20', '/utf-8' ]
include = [
    'deps\google-googletest-v1.15.2\googlemock',
    'deps\google-googletest-v1.15.2\googlemock\include',
    'deps\google-googletest-v1.15.2\googletest',
    'deps\google-googletest-v1.15.2\googletest\include'
]
modules = []
sources = [
    'deps\google-googletest-v1.15.2\googletest\src\gtest-all.cc',
    'deps\google-googletest-v1.15.2\googlemock\src\gmock-all.cc'
]

[build.test]
base_path = ''
cflags = [ '/DDEBUG', '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/FS', '/std:c++20', '/utf-8' ]
include = [
    'deps\evanwporter-cracklib-v0.0.3\include',
    'deps\gabime-spdlog-v1.15.1\include',
    'deps\google-googletest-v1.15.2\googlemock',
    'deps\google-googletest-v1.15.2\googlemock\include',
    'deps\google-googletest-v1.15.2\googletest',
    'deps\google-googletest-v1.15.2\googletest\include',
    'deps\kuba---zip-v0.3.3\src',
    'deps\nlohmann-json-v3.11.3\single_include',
    'deps\p-ranav-argparse-v3.2\include',
    'deps\p-ranav-glob-v0.3\single_include',
    'include'
]
modules = []
sources = [ 'tests\internal\muuk_test.cpp' ]

