[package]
name = "muuk"
version = "1.0.0"

[scripts]
hello = "echo Hello!"

[library.muuk]
include = ["include"]
sources = [
    "src/muuk.cpp",
    "src/util.cpp",
    "src/logger.cpp",
    "src/muukfiler.cpp",
    "src/muukbuilder.cpp",
    "src/ninjagen.cpp",
    "src/muuklockgen.cpp",
]
deps = ["prototyping/deps/test_deps/bcwrdll.ixx"]

[library.muuk.dependencies]
argparse = { version = "v3.2", git = "https://github.com/p-ranav/argparse.git", muuk_path = "deps/" }
glob = { version = "v0.3", git = "https://github.com/p-ranav/glob.git" }
spdlog = { version = "v1.15.1", git = "https://github.com/gabime/spdlog.git" }
zip = { "version" = "v0.3.3", git = "https://github.com/kuba--/zip.git" }
json = { "version" = "v3.11.3", git = "https://github.com/nlohmann/json.git" }
cracklib = { version = "v0.0.3", git = "https://github.com/evanwporter/cracklib.git" }

[build.bin]
dependencies = { "muuk" = "v1.0.0" }
sources = ["src/main.cpp"]
gflags = ["/std:c++20", "/utf-8", "/EHsc", "/FS"]

[build.test]
dependencies = { "muuk" = "v1.0.0", "googletest" = { version = "v1.15.2", git = "https://github.com/google/googletest.git" } }
sources = ["tests/internal/muuk_test.cpp"]
executable = "muuk_tests"
include = []
gflags = ["/std:c++20", "/utf-8", "/EHsc", "/FS"]

[clean]
patterns = ["*.obj", "*.lib", "*.pdb"]
