[build.bin]
base_path = ''
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/std:c++20', '/utf-8' ]
include = [
    'include',
    'modules/cracklib/include',
    'modules/gabime-spdlog-v1.15.1/include',
    'modules/kuba---zip-v0.3.3/src',
    'modules/nlohmann-json-v3.11.3/single_include',
    'modules/p-ranav-argparse-v3.2/include',
    'modules/p-ranav-glob-v0.0.1/single_include'
]
sources = [ 'src/main.cpp' ]

[build.test]
base_path = ''
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/std:c++20', '/utf-8' ]
include = [
    'include',
    'modules/cracklib/include',
    'modules/gabime-spdlog-v1.15.1/include',
    'modules/google-googletest-v1.15.2/googlemock',
    'modules/google-googletest-v1.15.2/googlemock/include',
    'modules/google-googletest-v1.15.2/googletest',
    'modules/google-googletest-v1.15.2/googletest/include',
    'modules/kuba---zip-v0.3.3/src',
    'modules/nlohmann-json-v3.11.3/single_include',
    'modules/p-ranav-argparse-v3.2/include',
    'modules/p-ranav-glob-v0.0.1/single_include'
]
sources = [ 'tests/internal/muuk_test.cpp' ]

[library.argparse]
base_path = 'modules/p-ranav-argparse-v3.2'
cflags = []
include = [ 'modules/p-ranav-argparse-v3.2/include' ]
sources = []

[library.glob]
base_path = 'modules/p-ranav-glob-v0.0.1'
cflags = []
include = [ 'modules/p-ranav-glob-v0.0.1/single_include' ]
sources = []

[library.googletest]
base_path = 'modules/google-googletest-v1.15.2'
cflags = []
include = [
    'modules/google-googletest-v1.15.2/googlemock',
    'modules/google-googletest-v1.15.2/googlemock/include',
    'modules/google-googletest-v1.15.2/googletest',
    'modules/google-googletest-v1.15.2/googletest/include'
]
sources = [
    'modules/google-googletest-v1.15.2/googletest/src/gtest-all.cc',
    'modules/google-googletest-v1.15.2/googlemock/src/gmock-all.cc'
]

[library.json]
base_path = 'modules/nlohmann-json-v3.11.3'
cflags = []
include = [ 'modules/nlohmann-json-v3.11.3/single_include' ]
sources = []

[library.muuk]
base_path = ''
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/std:c++20', '/utf-8' ]
include = [
    'include',
    'modules/cracklib/include',
    'modules/gabime-spdlog-v1.15.1/include',
    'modules/kuba---zip-v0.3.3/src',
    'modules/nlohmann-json-v3.11.3/single_include',
    'modules/p-ranav-argparse-v3.2/include',
    'modules/p-ranav-glob-v0.0.1/single_include'
]
sources = [
    'src/muuk.cpp',
    'src/util.cpp',
    'src/logger.cpp',
    'src/muukfiler.cpp',
    'src/muukbuilder.cpp',
    'src/ninjagen.cpp',
    'src/muuklockgen.cpp',
    'modules/cracklib/src/cracklib.cpp'
]

[library.spdlog]
base_path = 'modules/gabime-spdlog-v1.15.1'
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/std:c++20', '/utf-8' ]
include = [ 'modules/gabime-spdlog-v1.15.1/include' ]
sources = [
    'modules/gabime-spdlog-v1.15.1/src/async.cpp',
    'modules/gabime-spdlog-v1.15.1/src/cfg.cpp',
    'modules/gabime-spdlog-v1.15.1/src/spdlog.cpp',
    'modules/gabime-spdlog-v1.15.1/src/color_sinks.cpp',
    'modules/gabime-spdlog-v1.15.1/src/stdout_sinks.cpp',
    'modules/gabime-spdlog-v1.15.1/src/bundled_fmtlib_format.cpp',
    'modules/gabime-spdlog-v1.15.1/src/file_sinks.cpp'
]

[library.zip]
base_path = 'modules/kuba---zip-v0.3.3'
cflags = []
include = [ 'modules/kuba---zip-v0.3.3/src' ]
sources = [ 'modules/kuba---zip-v0.3.3/src/zip.c' ]