[library.argparse]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\argparse\include' ]
libs = []
modules = []
sources = []

[library.cracklib]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\cracklib\include' ]
libs = []
modules = []
sources = [ 'deps\cracklib\src\cracklib.cpp' ]

[library.glob]
base_path = 'deps/glob'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\glob\include' ]
libs = []
modules = []
sources = [ 'deps\glob\src\glob.cpp' ]

[library.json]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\json\single_include\' ]
libs = []
modules = []
sources = []

[library.spdlog]
base_path = 'deps'
cflags = [
    '/DNDEBUG',
    '/DSPDLOG_COMPILED_LIB',
    '/DSPDLOG_USE_STD_FORMAT',
    '/EHsc',
    '/FS',
    '/GL',
    '/Gy',
    '/O2',
    '/Oi',
    '/std:c++20',
    '/utf-8'
]
include = [ 'deps\spdlog\include' ]
libs = []
modules = []
sources = [
    'deps\spdlog\src\async.cpp',
    'deps\spdlog\src\cfg.cpp',
    'deps\spdlog\src\spdlog.cpp',
    'deps\spdlog\src\color_sinks.cpp',
    'deps\spdlog\src\stdout_sinks.cpp',
    'deps\spdlog\src\bundled_fmtlib_format.cpp',
    'deps\spdlog\src\file_sinks.cpp'
]

[library.tomlplusplus]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\tomlplusplus\include' ]
libs = []
modules = []
sources = []

[library.zip]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [ 'deps\zip\src' ]
libs = []
modules = []
sources = [ 'deps\zip\src\zip.c' ]

[library.muuk]
base_path = ''
cflags = [
    '/DNDEBUG',
    '/DSPDLOG_COMPILED_LIB',
    '/DSPDLOG_USE_STD_FORMAT',
    '/EHsc',
    '/FS',
    '/GL',
    '/Gy',
    '/O2',
    '/Oi',
    '/std:c++20',
    '/utf-8'
]
include = [
    'deps\argparse\include',
    'deps\cracklib\include',
    'deps\glob\include',
    'deps\json\single_include\',
    'deps\spdlog\include',
    'deps\tomlplusplus\include',
    'deps\zip\src',
    'include'
]
libs = []
modules = []
sources = [
    'src\muuker.cpp',
    'src\util.cpp',
    'src\logger.cpp',
    'src\muukfiler.cpp',
    'src\muukbuilder.cpp',
    'src\ninjagen.cpp',
    'src\muuklockgen.cpp'
]

[build.bin]
base_path = ''
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/FS', '/std:c++20', '/utf-8' ]
include = [
    'deps\argparse\include',
    'deps\cracklib\include',
    'deps\glob\include',
    'deps\json\single_include\',
    'deps\spdlog\include',
    'deps\tomlplusplus\include',
    'deps\zip\src',
    'include'
]
libs = []
modules = []
sources = [ 'src\main.cpp' ]

[library.googletest]
base_path = 'deps'
cflags = [ '/DNDEBUG', '/EHsc', '/FS', '/GL', '/Gy', '/O2', '/Oi', '/std:c++20', '/utf-8' ]
include = [
    'deps\googletest\googlemock',
    'deps\googletest\googlemock\include',
    'deps\googletest\googletest',
    'deps\googletest\googletest\include'
]
libs = []
modules = []
sources = [ 'deps\googletest\googletest\src\gtest-all.cc', 'deps\googletest\googlemock\src\gmock-all.cc' ]

[build.test]
base_path = ''
cflags = [ '/DSPDLOG_COMPILED_LIB', '/DSPDLOG_USE_STD_FORMAT', '/EHsc', '/FS', '/std:c++20', '/utf-8' ]
include = [
    'deps\argparse\include',
    'deps\cracklib\include',
    'deps\glob\include',
    'deps\googletest\googlemock',
    'deps\googletest\googlemock\include',
    'deps\googletest\googletest',
    'deps\googletest\googletest\include',
    'deps\json\single_include\',
    'deps\spdlog\include',
    'deps\tomlplusplus\include',
    'deps\zip\src',
    'include'
]
libs = []
modules = []
sources = [ 'tests\internal\muuk_test.cpp', 'tests\internal\mockmuukfiler.cpp' ]

