[build]
include = ['include']
lflags = ['/std:c++20', '/utf-8', '/EHsc']
libflags = ['/std:c++20', '/utf-8', '/EHsc']
sources = [
    'src/main.cpp',
    'src/muuk.cpp',
    'src/util.cpp',
    'src/logger.cpp',
    'src/muukfiler.cpp',
    'src/muukbuilder.cpp',
    'src/ninjagen.cpp',
    'src/muuklockgen.cpp',
]

[clean]
patterns = ['*.lib']

[dependencies]
gabime-spdlog = 'v1.15.0'
google-googletest = 'v1.15.2'
kuba---zip = 'v0.3.3'
nlohmann-json = 'v3.11.3'
p-ranav-argparse = 'v3.2'

[package]
name = 'muuk'

[scripts]
greet = 'echo hello world > "output.txt'
