[package]
name = "cracklib"
version = "0.0.3"

[library.cracklib]
include = ['cracklib/include']
sources = ['cracklib/src/cracklib.cpp']

[build.rarcrack]
dependencies = { "muuk" = "v0.0.3" }
sources = ['src/main.cpp']
