[package]
name = 'googletest'
version = "v1.15.2"

[library.googletest]
sources = [
    # "googletest/src/gtest_main.cc",
    "googletest/googletest/src/gtest-all.cc",
    "googletest/googlemock/src/gmock-all.cc",
    # "googlemock/src/gmock_main.cc",
]
include = [
    'googletest/googletest/include',
    'googletest/googletest',
    "googletest/googlemock/include",
    "googletest/googlemock",
]
