[package]
name = 'spdlog'
version = 'v1.15.1'

[library.spdlog]
include = ["spdlog/include"]
sources = [
    "spdlog/src/async.cpp",
    "spdlog/src/cfg.cpp",
    "spdlog/src/spdlog.cpp",
    "spdlog/src/color_sinks.cpp",
    "spdlog/src/stdout_sinks.cpp",
    "spdlog/src/bundled_fmtlib_format.cpp",
    "spdlog/src/file_sinks.cpp",
]
cflags = [
    "/DSPDLOG_COMPILED_LIB",
    "/DSPDLOG_USE_STD_FORMAT",
    "/std:c++20",
    "/EHsc",
    "/utf-8",
]
