[package]
name = 'toml11'
author = 'ToruNiina'
license = 'MIT'
version = 'a01fe3b4c14c6d7b99ee3f07c9e80058c6403097'
git = 'https://github.com/ToruNiina/toml11.git'

[library]
include = ['include']
sources = ["src/*.cpp"]
cflags = ['/DTOML11_COMPILE_SOURCES']

# [external]
# type = 'cmake'
# outputs = [
#     { path = "src/toml11.lib", profile = "debug" },
#     { path = "src/toml11.lib", profile = "release" },
# ]
# args = ['-DCMAKE_CXX_STANDARD=20']
