[package]
name = 'spdlog'
version = 'v1.15.1'

[library.spdlog]
include = ["include"]
sources = [
    "src/async.cpp",
    "src/cfg.cpp",
    "src/spdlog.cpp",
    "src/color_sinks.cpp",
    "src/stdout_sinks.cpp",
    "src/bundled_fmtlib_format.cpp",
    "src/file_sinks.cpp",
]
libflags = [
    "/DSPDLOG_COMPILED_LIB",
    "/DSPDLOG_USE_STD_FORMAT",
    "/std:c++20",
    "/EHsc",
    "/utf-8",
]
lflags = [
    "/DSPDLOG_COMPILED_LIB",
    "/DSPDLOG_USE_STD_FORMAT",
    "/std:c++20",
    "/EHsc",
    "/utf-8",
]
