[package]
name = 'googletest'
version = "v1.15.2"

[library.googletest]
sources = [
    # "googletest/src/gtest_main.cc",
    "googletest/src/gtest-all.cc",
    "googlemock/src/gmock-all.cc",
    # "googlemock/src/gmock_main.cc",
]
include = [
    'googletest/include',
    'googletest',
    "googlemock/include",
    "googlemock",
]
lflags = ["/std:c++20", "/EHsc"]
libflags = ["/std:c++20", "/EHsc"]
