[package]
name = 'dr_libs'
author = 'mackron'
license = 'NOASSERTION'
version = '9cb7092ac8c75a82b5c6ea72652ca8d0091d7ffa'
git = 'https://github.com/mackron/dr_libs.git'

[library]
include = ['include']
sources = [
]
