[package]
name = 'argparse'
revision = 'd924b84eba1f0f0adf38b20b7b4829f6f65b6570'
version = 'd924b84eba1f0f0adf38b20b7b4829f6f65b6570'

[library]
include = ['include']

[platform.linux]
cflags = []

[compiler.clang]
cflags = ['-std=c++20']
