[package]
name = 'argparse'
version = 'd924b84eba1f0f0adf38b20b7b4829f6f65b6570'
git = 'https://github.com/p-ranav/argparse.git'

[library]
include = ['include']

[platform.linux]
cflags = []

[compiler.clang]
cflags = ['-std=c++20']
