// version.h
#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 5

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION TOSTRING(APP_VERSION_MAJOR) "." TOSTRING(APP_VERSION_MINOR) "." TOSTRING(APP_VERSION_PATCH)
