name: install-and-build-from-artifact

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Install + Build via muuk (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Find latest successful run of windows-ninja
    #   id: find-run
    #   shell: pwsh
    #   run: |
    #     $run = gh run list --workflow build_win.yaml --branch main --limit 1 --json databaseId | ConvertFrom-Json
    #     echo "run_id=$($run[0].databaseId)" >> $env:GITHUB_OUTPUT
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Download bin-windows artifact from that run
    #   run: |
    #     gh run download ${{ steps.find-run.outputs.run_id }} --name bin-windows
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download muuk-windows.zip from latest release
      shell: pwsh
      run: |
        $release = gh release view --json assets -q ".assets[] | select(.name == ``muuk-windows.zip``) | .url"
        Invoke-WebRequest -Uri $release -OutFile muuk-windows.zip
        Expand-Archive -Path muuk-windows.zip -DestinationPath .
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  


    - name: Make muuk executable available
      run: Copy-Item .\bin.exe .\muuk.exe

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89

    - name: Install dependencies with muuk
      run: .\muuk.exe install

    - name: Ensure build/release directory exists
      run: New-Item -ItemType Directory -Path build/release -Force

    - name: Build project with muuk (MSVC Release)
      run: .\muuk.exe build -c msvc -p release
    
    - name: Copy muuk.exe
      run: copy build/release/bin/bin.exe muuk.exe

    - name: Compress built executables
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      with:
        files: muuk.exe
        dest: muuk-windows.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: muuk-windows
        path: muuk-windows.zip

    - name: Upload Release (if tag)
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: muuk-windows.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
